name = "control_theory"
version = "0.1.0"
defaultTargets = ["control_theory"]

[[lean_lib]]
name = "ControlTheory"

[[lean_exe]]
name = "control_theory"
root = "Main"


[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"